name = "LeanToDo"
version = "0.1.0"
defaultTargets = ["leantodo"]

[[lean_exe]]
name = "leantodo"
root = "Main"

[[require]]
name = "leansqlite"
git = "https://github.com/leanprover/leansqlite"
rev = "main"
