name = "LeanToDo"
version = "0.1.0"
defaultTargets = ["leantodo"]

[leanOptions]
autoImplicit = false

[[lean_exe]]
name = "leantodo"
root = "Main"
buildType = "relWithDebInfo"

[[lean_lib]]
name = "LeanToDo"
buildType = "relWithDebInfo"

[[require]]
name = "leansqlite"
git = "https://github.com/leanprover/leansqlite"
rev = "main"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.27.0"
